name: Events Demo
on:
  pull_request:
    types: [opened]
    branches: [main, dev-*, feat/**] # dev-new, dev-this-is-new, # feat/news, feat/neww/button
  workflow_dispatch:
  push:
    branches: [main, dev-*, feat/**] # dev-new, dev-this-is-new, # feat/news, feat/neww/button
    paths-ignore: # Ignore changes to these files
      - "README.md"
      - ".github/workflows/demo1.yml"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
